
name: Deploy Docs

on:
  push:
    branches:
      # make sure this is the branch you are using
      - main

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # if your docs needs submodules, uncomment the following line
          # submodules: true

      - name: Clear temp
        run: rm -rf docs/src/.vuepress/.temp && rm -rf /docs/src/.vuepress/.cache && rm -rf /docs/node_modules && rm -rf /docs/pnpm-lock.yaml
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache-dependency-path: docs/

      - name: Install Deps
        working-directory: docs/
        run: npm install

      - name: Build Docs
        working-directory: docs/
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: npm run docs:build

      - name: Deploy Docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # This is the branch where the docs are deployed to
          branch: gh-pages
          folder: docs/src/.vuepress/dist

