name: Deploy Docs

on:
  push:
    branches:
      # make sure this is the branch you are using
      - main

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Clear caches
        run: rm -rf node_modules pnpm-lock.yaml src/.vuepress/.temp src/.vuepress/.cache

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup pnpm 
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 7
          run_install: |
            - recursive: true
              args: [--no-frozen-lockfile, --strict-peer-dependencies]
            - args: [--global, @vuepress/bundler-vite@2.0.0-beta.51]

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache-dependency-path: docs/
          cache: pnpm
      
      - name: Build Docs
        working-directory: docs/
        run: pnpm run docs:build

      - name: Deploy Docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # This is the branch where the docs are deployed to
          branch: gh-pages
          folder: docs/src/.vuepress/dist

